package most.voip.api.enums;


public enum VoipEvent {
	
  LIB_INITIALIZING,
  LIB_INITIALIZED,
  LIB_INITIALIZATION_FAILED,
  LIB_DEINITIALIZING,
  LIB_DEINITIALIZE_DONE,
  LIB_DEINITIALIZE_FAILED,
  //CONNECTING,
  //CONNECTED,
  LIB_CONNECTION_FAILED,  // TIMEOUT during account registration request on the remote Sip Server
  ACCOUNT_REGISTERING,
  ACCOUNT_UNREGISTERING,
  ACCOUNT_REGISTERED,   
  ACCOUNT_UNREGISTERED ,
  ACCOUNT_REGISTRATION_FAILED,
  ACCOUNT_UNREGISTRATION_FAILED,
  BUDDY_SUBSCRIBING , // ex REMOTE_USER_SUBSCRIBING
  BUDDY_SUBSCRIPTION_FAILED,  //ex  REMOTE_USER_SUBSCRIBING_FAILED
  BUDDY_SUBSCRIBED, // ex REMOTE_USER_SUBSCRIBED
  BUDDY_CONNECTED , // ex REMOTE_USER_CONNECTED
  BUDDY_DISCONNECTED, // ex REMOTE_USER_DISCONNECTED
  BUDDY_HOLDING,  // ex CALL_REMOTE_HOLDING
  CALL_DIALING,   
  CALL_INCOMING,
  CALL_INCOMING_REJECTED,
  CALL_ACTIVE,
  CALL_HOLDING,
  CALL_UNHOLDING,
  CALL_HANGUP,
  CALL_REMOTE_HANGUP ,
  REMOTE_DISCONNECTION_HANGUP
}
   
