#!/bin/bash
echo  Building Most Voip Documentation ...
echo  Building Python Documentation ...
PYTHONPATH=../python/src/ make html
echo  Building Android Documentation ...
javasphinx-apidoc -fo android_docs/api/ ../android/src/AndroidVoipLib/src/most/voip/

